# Generated by Django 5.1.7 on 2025-04-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_menuitem_alter_order_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('preparing', 'Preparing'), ('out-for-delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
